# Generated by Django 4.0 on 2022-06-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_on_payment',
            field=models.BooleanField(default=True),
        ),
    ]
