# Generated by Django 4.0.5 on 2022-07-22 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0004_association_notify_user_payments'),
        ('profiles', '0004_passwordresetlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOptInContributionFields',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_field_id', models.UUIDField()),
                ('state', models.CharField(choices=[('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='REQUESTED', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_opt_ins', to=settings.AUTH_USER_MODEL)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associations.association')),
                ('contrib_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opted_in_users', to='associations.association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opted_in_contrib_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
