"""
Django settings for apps project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

import environ

from glob import glob


BASE_DIR = Path(__file__).resolve().parent.parent

# Read environment variables from correct location
environ.Env.read_env(env_file=f'{BASE_DIR}/.env')

ENV = environ.FileAwareEnv()    # This allows better environment variables finding

ENVIRONMENT = ENV('ENVIRONMENT')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ENV('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENV.bool('DEBUG')

ALLOWED_HOSTS = ENV.list('ALLOWED_HOSTS')

CORS_ALLOWED_ORIGINS = ENV.list('CORS_ALLOWED_ORIGINS')

# Environment specific hosts
API_HOST = ENV.str('API_HOST')
FRONT_END_HOST = ENV.str('FRONT_END_HOST')

BASE_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

PACKAGE_APPS = [
    'django_filters',
    'rest_framework',
    'rest_framework_json_api',
    'django_extensions',
    'corsheaders',
    'anymail',
]

DJANGHI_APPS = [
    'apps.profiles',
    'apps.associations',
    'apps.payments',
]

INSTALLED_APPS = BASE_APPS + PACKAGE_APPS + DJANGHI_APPS

BASE_MIDDLEWARES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

PACKAGE_MIDDLEWARES = [
    'corsheaders.middleware.CorsMiddleware',
]

CUSTOM_MIDDLEWARES = [
    'apps.middlewares.CustomAuthenticationMiddleware',
]

MIDDLEWARE = BASE_MIDDLEWARES + PACKAGE_MIDDLEWARES + CUSTOM_MIDDLEWARES

ROOT_URLCONF = 'apps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            f'{BASE_DIR}/apps/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATICFILES_DIRS = [
    f'{BASE_DIR}/apps/statics',
]

STATIC_ROOT = '/var/djanghi/static'

FIXTURE_DIRS = [
    f'{BASE_DIR}/tests/fixtures',
]


WSGI_APPLICATION = 'apps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': ENV.db(
        default=f"psql:"
                f"//{ENV('POSTGRES_USER')}:"
                f"{ENV('POSTGRES_PASSWORD')}@"
                f"{ENV('POSTGRES_HOST')}:"
                f"{ENV('DB_PORT')}/{ENV('POSTGRES_DB')}"
    ),
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


GDAL_LIBRARY_PATH = glob('/usr/lib/libgdal.so.*')[0]
GEOS_LIBRARY_PATH = glob('/usr/lib/libgeos_c.so.*')[0]

DEFAULT_REGISTRATION_LINK_LIFE = 10     # 10 Days

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

AUTH_USER_MODEL = 'profiles.User'
AUTHENTICATION_BACKENDS = ['apps.extensions.backend.DjanghiModelBackend']
