# Generated by Django 3.2.12 on 2022-02-24 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='association',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_associations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membercontributionfield',
            name='member_can_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membercontributionfield',
            name='required_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('rapport', models.TextField(blank=True, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='associations.association')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_meetings', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_meetings', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaded_meetings', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
