# Generated by Django 3.2.9 on 2021-12-27 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membercontributionfield',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_contribution_fields', to='associations.association'),
        ),
        migrations.AddConstraint(
            model_name='membercontributionfield',
            constraint=models.UniqueConstraint(fields=('name', 'association'), name='unique_contribution_name_by_association'),
        ),
    ]
