# Generated by Django 4.0 on 2022-06-21 22:39
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0002_add_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='email_from',
            field=models.EmailField(default=settings.DEFAULT_FROM_EMAIL, max_length=254),
        ),
    ]
