# Generated by Django 4.0 on 2022-06-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0003_alter_association_email_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='notify_user_payments',
            field=models.BooleanField(default=True),
        ),
    ]
