# Generated by Django 3.2.12 on 2022-02-24 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0002_add_meeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_type', models.CharField(choices=[('COST', 'Subtractive for the user'), ('PAYMENT', 'Additive for the user')], default='PAYMENT', max_length=15)),
                ('amount', models.FloatField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_payments', to='associations.association')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_membership_payments', to=settings.AUTH_USER_MODEL)),
                ('membership_payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_payments', to='associations.membercontributionfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
